# appveyor.yml
---
environment:
  matrix:
  - TOXENV: py310

build: off

install:
- pip install chardet
- pip install ftfy==4.4.3
- pip install idna
- pip install lxml
- pip install requests
- pip install urllib3
- pip install wcwidth
- pip install XlsxWriter
- pip install dashtable
- pip install beautifulsoup4
- pip install tox

test_script:
  - py -m tox
